#include <stm32g431xx.h>

int main()
{
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PA;

	EXTI->IMR1 |= EXTI_IMR1_IM0;
	EXTI->RTSR1 |= EXTI_RTSR1_RT0;

	GPIOA->MODER &= ~(GPIO_MODER_MODE5_Msk | GPIO_MODER_MODE6_Msk | GPIO_MODER_MODE7_Msk | GPIO_MODER_MODE8_Msk);
	GPIOA->MODER |= (1<<GPIO_MODER_MODE5_Pos | 1<<GPIO_MODER_MODE6_Pos | 1<<GPIO_MODER_MODE7_Pos | 1<<GPIO_MODER_MODE8_Pos);
	GPIOA->MODER &= ~(GPIO_MODER_MODE0_Msk);

	NVIC_EnableIRQ(EXTI0_IRQn);
	while(1)
	{

	}
}

void EXTI0_IRQHandler()
{
	GPIOA->ODR ^= GPIO_ODR_OD5;
	EXTI->PR1 = EXTI_PR1_PIF0;
}
